# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "deps:"
      include: "scope"
