# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2

updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "yearly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"

