name: Release
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    # if the workflow run was successful and the branch is main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    steps:
      # Checkout action is required for token to persist
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE }}

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.32.0
        with:
          github_token: ${{ secrets.RELEASE }}
          # Remember to copy the [semantic_release] section from pyproject.toml
          # as well
          # To enable pypi,
          # 1) Set upload_to_pypi to true in  pyproject.toml and
          # 2) Set the pypi_token in the repo
          # 3) Uncomment the two lines below
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
