# This workflow will
# 1) Update the version number in pyproject.toml based on the commit history
# 2) Create a git tag
# 3) Create a release on GitHub
# 4) Upload the package to PyPI

name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      # Checkout action is required for token to persist
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.33.2
        with:
          github_token: ${{ secrets.PAT }}
          # Remember to copy the [tool.semantic_release] section from pyproject.toml
          # as well
          # To enable pypi,
          # 1) Set upload_to_pypi to true in  pyproject.toml and
          # 2) Set the pypi_token in the repo
          # 3) Uncomment the two lines below
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_API_TOKEN }}
