# THIS ACTION WILL:
  # 1. Install dependencies
  # 2. Run static type checker

# SETUP:
  # None required except for the Makefile

name: static_type_checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  static_type_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.12

      - name: Run static type checker
        shell: bash
        run: |
          make static-type-check
