# Workflow for running Tutorials on GitHub Actions
# Work by running converting all .ipynb to .py
# then run all .py in the tutorials folder

name: Run Tutorials
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  RunNotebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install .[all]
          pip install -r tutorials/requirements.txt
      - name: Convert to py
        run: |
          jupyter nbconvert --to python ./tutorials/*.ipynb
      - name: Run notebooks
        # run all python script in tutorials folder
        run: |
          for f in tutorials/*.py; do python "$f"; done
